package bll;

import be.Category;
import be.Movie;
import dal.CategoryDAO;
import dal.MovieDAO;

import java.util.ArrayList;
import java.util.List;

/**
 * Business Logic Layer (BLL) manager for Movies and Categories.
 * The controller talks to this class instead of calling DAOs directly.
 *
 * The goal is to keep database details inside the DAL layer and
 * keep the UI/controller code clean and focused on the user interface.
 */
public class MovieManager {

    // Data access objects (DAL layer)
    private final MovieDAO movieDao = new MovieDAO();
    private final CategoryDAO categoryDao = new CategoryDAO();

    /**
     * Loads all movies from the database, including their categories.
     */
    public List<Movie> getAllMovies() {
        return movieDao.getAllMovies();
    }

    /**
     * Loads all categories from the database.
     */
    public List<Category> getAllCategories() {
        return categoryDao.getAllCategories();
    }

    // ---------- MOVIE CRUD ----------

    /**
     * Creates a new movie and assigns the selected categories.
     * Any "last view" value should be handled by the database (DATE) or set later.
     */
    public void createMovie(String title,
                            double imdb,
                            double personal,
                            String fileLink,
                            List<Category> categories) {

        // Basic defensive checks to avoid invalid data passing to DAL
        if (title == null || title.isBlank()) {
            throw new IllegalArgumentException("Movie title cannot be empty.");
        }
        if (categories == null) {
            categories = new ArrayList<>();
        }

        // ID -1 means "not stored yet" (it will be generated by the database)
        // lastView is intentionally left empty; it can be updated when the movie is viewed.
        Movie newMovie = new Movie(-1, title.trim(), personal, imdb, fileLink, "");

        // Pass entity + categories to the DAO, which handles DB insert and relations
        movieDao.createMovie(newMovie, categories);
    }

    /**
     * Updates an existing movie and its category relationships.
     */
    public void updateMovie(Movie movie, List<Category> categories) {
        if (movie == null) {
            throw new IllegalArgumentException("Movie cannot be null.");
        }
        if (categories == null) {
            categories = new ArrayList<>();
        }
        movieDao.updateMovie(movie, categories);
    }

    /**
     * Deletes the movie and any related category links in the database.
     */
    public void deleteMovie(Movie movie) {
        if (movie == null) {
            throw new IllegalArgumentException("Movie cannot be null.");
        }
        movieDao.deleteMovie(movie);
    }

    // ---------- CATEGORY CRUD ----------

    /**
     * Creates a new category.
     */
    public void createCategory(String name) {
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Category name cannot be empty.");
        }
        categoryDao.createCategory(name.trim());
    }

    /**
     * Deletes the given category.
     */
    public void deleteCategory(Category category) {
        if (category == null) {
            throw new IllegalArgumentException("Category cannot be null.");
        }
        categoryDao.deleteCategory(category);
    }

    // ---------- SEARCH (simple title search) ----------

    /**
     * Simple search by title.
     * Note: In JavaFX, filtering is often done in the UI layer using FilteredList.
     * This method is still useful if you want a plain search without TableView filtering.
     */
    public List<Movie> searchMovies(String query) {
        List<Movie> allMovies = getAllMovies();
        List<Movie> results = new ArrayList<>();

        if (query == null || query.isBlank()) {
            return allMovies;
        }

        String q = query.trim().toLowerCase();

        for (Movie m : allMovies) {
            String title = (m.getTitle() == null) ? "" : m.getTitle().toLowerCase();
            if (title.contains(q)) {
                results.add(m);
            }
        }

        return results;
    }

    // ---------- LAST VIEW ----------

    /**
     * Updates the "last viewed" date for a movie.
     * This should normally store the current date in the database (SQL DATE).
     */
    public void updateLastView(int id) {
        movieDao.updateLastView(id);
    }
}
